Repository rapidsai/libgdf, pull requests merged in 2018-08, with the labels that each got.

#87 [REVIEW] Fix warnings in sqls CUDA files
  include/sqls_rtti_comp.hpp
  src/sqls_ops.cu
  src/tests/sqls/sqls_g_tester.cu
Labels: 3 - Ready for Review

#88 [REVIEW] README Dependency Updates
  README.md
Labels: 3 - Ready for Review

#86 [REVIEW] Adding templates for Issues and Pull Requests
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3 - Ready for Review

#89 [REVIEW] Add Apache arrow 0.10 support
  CMakeLists.txt
  README.md
  cmake/Modules/ConfigureArrow.cmake
  cmake/Modules/FindArrow.cmake
  cmake/Templates/Arrow.CMakeLists.txt.cmake
  conda-recipes/libgdf/meta.yaml
  conda_environments/dev_py35.yml
  python/tests/test_hashing.py
  python/tests/test_ipc.py
  src/ipc.cu
  travisci/build_libgdf_cffi.sh
Labels: 3 - Ready for Review

#95 [REVIEW] Fixes #77 - test_hashing bug
  python/tests/test_hashing.py
Labels: 3 - Ready for Review

#98 [Review] Fea ext mem estimation - added an 2nd probe of the hash-table to estimate the number of common elements found
  src/hash-join/join_compute_api.h
  src/hash-join/join_kernels.cuh
  src/joining.h
Labels: 3 - Ready for Review

#99 [REVIEW] User defined selection between hash & sort based inner/left join
  CMakeLists.txt
  include/gdf/cffi/functions.h
  python/tests/test_joining.py
  python/tests/utils.py
  src/context.cpp
  src/joining.cu
  src/tests/join/join-tests.cu
  src/tests/join/tuple_vectors.h
Labels: 3 - Ready for Review

#113 [REVIEW] FIX Update Travis CI Script to Update apt Before libboost Install
  .travis.yml
Labels: 3 - Ready for Review, travis ci

#112 [REVIEW] Robust memory estimation is now in place
  src/join/hash/join_compute_api.h
Labels: 3 - Ready for Review

#101 [REVIEW] Fixes #81: remove Python 2.7 builds, add CUDA 9.2 builds, default to CUDA 9.2
  .travis.yml
  travisci/install-cuda-trusty.sh
Labels: 3 - Ready for Review, travis ci

#114 [REVIEW] Remove pytest-ci option from CMakeLists.txt
  CMakeLists.txt
Labels: 3 - Ready for Review, cmake, gpuCI, tests

#109 [Review] Quantiles Functionality
  CMakeLists.txt
  include/gdf/cffi/functions.h
  include/gdf/cffi/types.h
  include/quantiles.hpp
  src/quantiles.cu
  src/tests/CMakeLists.txt
  src/tests/quantiles/CMakeLists.txt
  src/tests/quantiles/quant_tester.cu
Labels: 3 - Ready for Review
